# fly.toml app configuration file generated for translator-relay on 2025-06-17T20:06:35+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'translator-relay'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2
  max_machines_running = 10
  processes = ['app']

# Auto-scaling configuration for production load
[http_service.concurrency]
  type = "requests"
  hard_limit = 100
  soft_limit = 80

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
